### ISSUE TITLE
doesn't build with sundials 5.1.0

### ISSUE THREAD

**Issue by flokli** [bmcage/odes#114]
I tried pointing scikits-odes to sundials 5.1.0, but it fails to compile:

### Python 2.7
```
/nix/store/fdgwwak9g61j6jyilqpiswih02llm81l-gfortran-wrapper-9.2.0/bin/gfortran -Wall -g -Wall -g -shared build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/scikits/odes/lsodimodule.o build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7/scikits/odes/fortranobject.o build/temp.linux-x86_64-2.7/scikits/odes/daepack/xerrwv.o build/temp.linux-x86_64-2.7/scikits/odes/daepack/vnorm.o build/temp.linux-x86_64-2.7/scikits/odes/daepack/stodi.o build/temp.linux-x86_64-2.7/scikits/odes/daepack/solsy.o build/temp.linux-x86_64-2.7/scikits/odes/daepack/prepji.o build/temp.linux-x86_64-2.7/scikits/odes/daepack/lsodi.o build/temp.linux-x86_64-2.7/scikits/odes/daepack/intdy.o build/temp.linux-x86_64-2.7/scikits/odes/daepack/ewset.o build/temp.linux-x86_64-2.7/scikits/odes/daepack/dlinpk.o build/temp.linux-x86_64-2.7/scikits/odes/daepack/ddaspk.o build/temp.linux-x86_64-2.7/scikits/odes/daepack/daux.o build/temp.linux-x86_64-2.7/scikits/odes/daepack/cfode.o build/temp.linux-x86_64-2.7/scikits/odes/daepack/ainvg.o -L/nix/store/m62n6i62f7vkman907blw7znjlkvla2b-gfortran-9.2.0-lib/lib -L/nix/store/m62n6i62f7vkman907blw7znjlkvla2b-gfortran-9.2.0-lib/lib -L/nix/store/bh447min7f6vqdw3x1iywr1vxyx4ix8y-python-2.7.17/lib -lpython2.7 -lgfortran -o build/lib.linux-x86_64-2.7/scikits/odes/lsodi.so
building 'scikits.odes.sundials.common_defs' extension
compiling C sources
C compiler: gcc -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC

creating build/temp.linux-x86_64-2.7/scikits/odes/sundials
compile options: '-I/nix/store/q1sxwhf9zysd4vhkxqzzh4l1sd28spaz-python2.7-numpy-1.16.5/lib/python2.7/site-packages/numpy/core/include -I/nix/store/bh447min7f6vqdw3x1iywr1vxyx4ix8y-python-2.7.17/include/python2.7 -c'
gcc: scikits/odes/sundials/common_defs.c
In file included from /nix/store/q1sxwhf9zysd4vhkxqzzh4l1sd28spaz-python2.7-numpy-1.16.5/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822,
                 from /nix/store/q1sxwhf9zysd4vhkxqzzh4l1sd28spaz-python2.7-numpy-1.16.5/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /nix/store/q1sxwhf9zysd4vhkxqzzh4l1sd28spaz-python2.7-numpy-1.16.5/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from scikits/odes/sundials/common_defs.c:631:
/nix/store/q1sxwhf9zysd4vhkxqzzh4l1sd28spaz-python2.7-numpy-1.16.5/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
scikits/odes/sundials/common_defs.c:641:10: fatal error: sundials/sundials_pcg.h: No such file or directory
  641 | #include "sundials/sundials_pcg.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: Command "gcc -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/nix/store/q1sxwhf9zysd4vhkxqzzh4l1sd28spaz-python2.7-numpy-1.16.5/lib/python2.7/site-packages/numpy/core/include -I/nix/store/bh447min7f6vqdw3x1iywr1vxyx4ix8y-python-2.7.17/include/python2.7 -c scikits/odes/sundials/common_defs.c -o build/temp.linux-x86_64-2.7/scikits/odes/sundials/common_defs.o -MMD -MF build/temp.linux-x86_64-2.7/scikits/odes/sundials/common_defs.o.d" failed with exit status 1
builder for '/nix/store/n8hmyyvyjhvlhxmjpb95j612kwgdyp92-python2.7-scikits.odes-2.4.0-9-g93075ae.drv' failed with exit code 1
error: build of '/nix/store/n8hmyyvyjhvlhxmjpb95j612kwgdyp92-python2.7-scikits.odes-2.4.0-9-g93075ae.drv' failed
```

### Python 3.7
```
/nix/store/fdgwwak9g61j6jyilqpiswih02llm81l-gfortran-wrapper-9.2.0/bin/gfortran -Wall -g -Wall -g -shared build/temp.linux-x86_64-3.7/build/src.linux-x86_64-3.7/scikits/odes/lsodimodule.o build/temp.linux-x86_64-3.7/build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/scikits/odes/fortranobject.o build/temp.linux-x86_64-3.7/scikits/odes/daepack/xerrwv.o build/temp.linux-x86_64-3.7/scikits/odes/daepack/vnorm.o build/temp.linux-x86_64-3.7/scikits/odes/daepack/stodi.o build/temp.linux-x86_64-3.7/scikits/odes/daepack/solsy.o build/temp.linux-x86_64-3.7/scikits/odes/daepack/prepji.o build/temp.linux-x86_64-3.7/scikits/odes/daepack/lsodi.o build/temp.linux-x86_64-3.7/scikits/odes/daepack/intdy.o build/temp.linux-x86_64-3.7/scikits/odes/daepack/ewset.o build/temp.linux-x86_64-3.7/scikits/odes/daepack/dlinpk.o build/temp.linux-x86_64-3.7/scikits/odes/daepack/ddaspk.o build/temp.linux-x86_64-3.7/scikits/odes/daepack/daux.o build/temp.linux-x86_64-3.7/scikits/odes/daepack/cfode.o build/temp.linux-x86_64-3.7/scikits/odes/daepack/ainvg.o -L/nix/store/m62n6i62f7vkman907blw7znjlkvla2b-gfortran-9.2.0-lib/lib -L/nix/store/m62n6i62f7vkman907blw7znjlkvla2b-gfortran-9.2.0-lib/lib -L/nix/store/ja04f3cmapzb3f2mvjrb883bfqclsirq-python3-3.7.6/lib -lpython3.7m -lgfortran -o build/lib.linux-x86_64-3.7/scikits/odes/lsodi.cpython-37m-x86_64-linux-gnu.so
building 'scikits.odes.sundials.common_defs' extension
compiling C sources
C compiler: gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC

creating build/temp.linux-x86_64-3.7/scikits/odes/sundials
compile options: '-I/nix/store/hzh4nqhzr0a86mh1dd8r806cq5sn95pn-python3.7-numpy-1.18.1/lib/python3.7/site-packages/numpy/core/include -I/nix/store/ja04f3cmapzb3f2mvjrb883bfqclsirq-python3-3.7.6/include/python3.7m -c'
gcc: scikits/odes/sundials/common_defs.c
In file included from /nix/store/hzh4nqhzr0a86mh1dd8r806cq5sn95pn-python3.7-numpy-1.18.1/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1832,
                 from /nix/store/hzh4nqhzr0a86mh1dd8r806cq5sn95pn-python3.7-numpy-1.18.1/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /nix/store/hzh4nqhzr0a86mh1dd8r806cq5sn95pn-python3.7-numpy-1.18.1/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from scikits/odes/sundials/common_defs.c:631:
/nix/store/hzh4nqhzr0a86mh1dd8r806cq5sn95pn-python3.7-numpy-1.18.1/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
scikits/odes/sundials/common_defs.c:641:10: fatal error: sundials/sundials_pcg.h: No such file or directory
  641 | #include "sundials/sundials_pcg.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: Command "gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/nix/store/hzh4nqhzr0a86mh1dd8r806cq5sn95pn-python3.7-numpy-1.18.1/lib/python3.7/site-packages/numpy/core/include -I/nix/store/ja04f3cmapzb3f2mvjrb883bfqclsirq-python3-3.7.6/include/python3.7m -c scikits/odes/sundials/common_defs.c -o build/temp.linux-x86_64-3.7/scikits/odes/sundials/common_defs.o -MMD -MF build/temp.linux-x86_64-3.7/scikits/odes/sundials/common_defs.o.d" failed with exit status 1
builder for '/nix/store/8721l6n8czwy6nmf10gyghkcnixifgqa-python3.7-scikits.odes-2.4.0-9-g93075ae.drv' failed with exit code 1
error: build of '/nix/store/8721l6n8czwy6nmf10gyghkcnixifgqa-python3.7-scikits.odes-2.4.0-9-g93075ae.drv' failed
```

cc @idontgetoutmuch

**Comment by flokli** [comment]
I'm sorry - seems nixpkgs still was on `2.4.0-9-g93075ae` instead of the latest release - It builds with 2.6.1. Sorry for the noise.
