### ISSUE TITLE
Upgrade to the latest sundials 4.1.0

### ISSUE THREAD

**Issue by idontgetoutmuch** [bmcage/odes#98]
I know this is a pain as I've had to do it for the Haskell bindings to sundials but it would be good if it happened :)

**Comment by bmcage** [comment]
Updating to the latest should not be as much work as updating to previous major release, but still, it does require to dedicate some time to it. Opening an issue is a good first step :-)

**Comment by bmcage** [comment]
Version 2.5.0 of Odes with sundials 4.1 support is released

**Comment by idontgetoutmuch** [comment]
Woohoo!

**Comment by bmcage** [comment]
@idontgetoutmuch sundials released 5.0.0 in oktober. No API changes that impact us, so current version of odes should just work with that. Nevertheless, some doc changes, see branch https://github.com/bmcage/odes/tree/sundials_5_0 will be released in the future.

**Comment by idontgetoutmuch** [comment]
> @idontgetoutmuch sundials released 5.0.0 in oktober. No API changes that impact us, so current version of odes should just work with that. Nevertheless, some doc changes, see branch https://github.com/bmcage/odes/tree/sundials_5_0 will be released in the future.

`scikits-odes` d0a700935455a024c0819eb9785cee2841fc07fe fails to build with `SUNDIALS` 5.0:

```
scikits/odes/sundials/common_defs.c:641:10: fatal error: 'sundials/sundials_pcg.h' file not found
#include "sundials/sundials_pcg.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~
```

And indeed

```
/Users/.../sundials/include/sunlinsol:
  total used in directory 176 available 9223372036849992776
  drwxr-xr-x  15 ...  staff   480  9 Dec 01:00 .
  drwxr-xr-x  13 ...  staff   416 21 May  2019 ..
  -rw-r--r--   1 ...  staff  2649  9 Dec 01:00 sunlinsol_band.h
  -rw-r--r--   1 ...  staff  5600  9 Dec 01:00 sunlinsol_cusolversp_batchqr.h
  -rw-r--r--   1 ...  staff  2983  9 Dec 01:00 sunlinsol_dense.h
  -rw-r--r--   1 ...  staff  5603  9 Dec 01:00 sunlinsol_klu.h
  -rw-r--r--   1 ...  staff  3379  9 Dec 01:00 sunlinsol_lapackband.h
  -rw-r--r--   1 ...  staff  3408  9 Dec 01:00 sunlinsol_lapackdense.h
  -rw-r--r--   1 ...  staff  4116  9 Dec 01:00 sunlinsol_pcg.h
  -rw-r--r--   1 ...  staff  4398  9 Dec 01:00 sunlinsol_spbcgs.h
  -rw-r--r--   1 ...  staff  4881  9 Dec 01:00 sunlinsol_spfgmr.h
  -rw-r--r--   1 ...  staff  4774  9 Dec 01:00 sunlinsol_spgmr.h
  -rw-r--r--   1 ...  staff  4498  9 Dec 01:00 sunlinsol_sptfqmr.h
  -rw-r--r--   1 ...  staff  4850  9 Dec 01:00 sunlinsol_superludist.h
  -rw-r--r--   1 ...  staff  4533  9 Dec 01:00 sunlinsol_superlumt.h
```

@bmcage given you say it "should just work", I wonder what I have done wrong.

**Comment by bmcage** [comment]
I was wrong with the 'no api changes', some header files are gone, but I originally did not uninstall, so my first impression was all keeps working.
In the end, quite some minor changes, see sundials_5_0 branch, which is ready. I added cvodes, idas in the wrapper, I'd like to add some basic test for that still before release.
